### ISSUE TITLE
Some questions about momentum update and hierarchical contrast loss

### ISSUE THREAD

**Issue by Shubao-Zhao** [xingyu617/SimTS_Representation_Learning#2]
Hi, dear Xiaochen:
Thank you and congratulations on your new progress in time series representation learning, which inspired me to think about whether crudely introducing contrastive learning into time series can really bring performance gains. For SIMTS, I have two small questions:
1. Does the hierarchical contrast loss lead to performance improvement?
2. I didn't find the momentum update encoder (self.net2) used.
Looking forward to your reply.

**Comment by xcvil** [comment]
Hello Jacks,

Thank you for your interest in our paper. Regarding your question:

1. We are conducting investigations and will publish the results online as soon as they are completed.
2. We did not apply the momentum encoder, and those codes are redundant. See [this commit](https://github.com/xingyu617/SimTS_Representation_Learning/commit/df0326145633cf6802b5ba67bddc3e49e054aa20).

Cheers,
SimTS Authors

**Comment by StatMixedML** [comment]
> We are conducting investigations and will publish the results online as soon as they are completed.

@xcvil I was curious if the hierarchical contrast loss increases the quality of the representations for downstream forecasting tasks. Have you had a chance to re-run the experiments using the new loss?

**Comment by axion66** [comment]
I'm also curious to know this, but @StatMixedML based on [ts2vec](https://arxiv.org/pdf/2106.10466), it improves the quality of the representaiton *though it's unclear it's true for SimTS architecture too.
