### ISSUE TITLE
Data Transformation in TensorDataset / DataLoader

### ISSUE THREAD

**Issue by StatMixedML** [xingyu617/SimTS_Representation_Learning#3]
Thanks again for the nice approach.

I was going through the [simts.py](https://github.com/xingyu617/SimTS_Representation_Learning/blob/main/simts.py#L205) file, noting that you use the [PretrainDataset](https://github.com/xingyu617/SimTS_Representation_Learning/blob/main/simts.py#L24) that transform the input series via jitter, scale and shift, instead of the standard `TensorDataset(torch.from_numpy(train_data).to(torch.float))` data. Any reasons for this? Maybe this is a left-over from the ablation study? At least for my dataset, the [non-transformed version](https://github.com/xingyu617/SimTS_Representation_Learning/blob/main/simts.py#L206) gave better results.

**Comment by xcvil** [comment]
Hi, thanks for your issue!

Yes, that is right. It is leftover. We only use the [PretrainDataset](https://github.com/xingyu617/SimTS_Representation_Learning/blob/main/simts.py#L24) for ablation experiments and [CoST](https://openreview.net/forum?id=PilZY3omXV2) comparison. The main results are obtained with [TensorDataset](https://github.com/xingyu617/SimTS_Representation_Learning/blob/2ab5572830539b54f29de5486706382d40b2e1db/simts.py#L208). See [this commit](https://github.com/xingyu617/SimTS_Representation_Learning/commit/2ab5572830539b54f29de5486706382d40b2e1db).
