### ISSUE TITLE
about how to use your code

### ISSUE THREAD

**Issue by yexianyao** [xingyu617/SimTS_Representation_Learning#4]
Thank you for your excellent work. I am a novice in time series analysis, and I would like to know how to use your code for time series prediction tasks. Could you please provide me with the necessary steps to do so? I have already downloaded the dataset you provided.

**Comment by xcvil** [comment]
Please refer to [this](https://github.com/xingyu617/SimTS_Representation_Learning/blob/main/train_simts.py) for pretraining.
