### ISSUE TITLE
您提供的dataset里没有后缀名为pkl的文件

### ISSUE THREAD

**Issue by hexiajunu** [xingyu617/SimTS_Representation_Learning#6]
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/electricity.pkl' 请问这个应该怎么解决？

**Comment by xcvil** [comment]
For efficiency, could you provide the entire error message?

**Comment by hexiajunu** [comment]
Traceback (most recent call last):
  File "E:\pycharm_file\SimTS_Representation_Learning-main\train_simts.py", line 95, in <module>
    all_train_data, all_train_labels, all_train_timestamps, all_test_data, all_test_labels, all_test_timestamps, delay = datautils.load_anomaly(args.dataset)
  File "E:\pycharm_file\SimTS_Representation_Learning-main\datautils.py", line 232, in load_anomaly
    res = pkl_load(f'datasets/{name}.pkl')
  File "E:\pycharm_file\SimTS_Representation_Learning-main\utils.py", line 50, in pkl_load
    with open(name, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/electricity.pkl'

**Comment by xcvil** [comment]
I see. In our work, we only focused on forecasting tasks. That is why we did not provide a dataset for anomaly detection.

**Comment by hexiajunu** [comment]
Ok, thanks for the answer



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiaochen ***@***.***&gt;; 
发送时间: 2023年5月29日(星期一) 晚上8:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xingyu617/SimTS_Representation_Learning] 您提供的dataset里没有后缀名为pkl的文件 (Issue #6)





 
I see. In our work, we only focused on forecasting tasks. That is why we did not provide a dataset for anomaly detection.

**Comment by xcvil** [comment]
Please refer to [this commit](https://github.com/xingyu617/SimTS_Representation_Learning/commit/3e98448dd6434eadbe4c0abbc41543afb349d163).
